chore!: refactor NewMsgPayForBlob to accept blobs
celestiaorg/celestia-app pull request #1197
Opened 2023-01-09 01:41 UTC by evan-forbes

## Overview

part of #388 and split off from #1154. This is just a minor refactor for `NewMsgPayForBlob` to accept a `tmproto.Blob`, instead of the individual components.

## Checklist

- [x] New and updated code has appropriate documentation
- [x] New and updated code has new and/or updated testing
- [x] Required CI checks are passing
- [x] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

2023-01-09 14:48 UTC, cmwaters requested changes

2023-01-10 01:08 UTC, evan-forbes commented on x/blob/types/payforblob.go
> +func NewMsgPayForBlob(signer string, blob *tmproto.Blob) (*MsgPayForBlob, error) {
> Now users need to import the tendermint repo as well which they might not have been doing. 

true! would a referenced type make this any better? added in 9dfae2502792e80540a67e4d150e50dc19656637
```go
type Blob = tmproto.Blob
```

> Blob also has the share version which users might be confused as to whether it's necessary or where to get it.

If the `NewBlob` function is used, do you think this is more palatable? There we add the default share version, at least until we have multiple share versions. I have also added a `DefaultShareVersion` constant with docs that specifically say to use that if someone is not sure which one to use. 9dfae2502792e80540a67e4d150e50dc19656637

Those are fair criticisms, but the alternative for multiple blobs is 
```go
func NewMsgPayForBlob(signer string, namespaces [][]byte, data [][]byte, shareversions []uint32)
```
and that feels really clunky to me

2023-01-10 01:28 UTC, evan-forbes commented
Do we also want to refactor https://github.com/celestiaorg/celestia-app/blob/f4f6a3adba8c1d31de13ab72d2b2d3ee522ba462/x/blob/types/payforblob.go#L143-L157
in a similar way?

2023-01-10 16:47 UTC, rootulp submitted a review, later dismissed

2023-01-10 16:47 UTC, rootulp commented on pkg/appconsts/appconsts.go
> +	DefaultShareVersion = ShareVersionZero
👍

2023-01-10 17:28 UTC, cmwaters commented on x/blob/types/payforblob.go
> +func NewMsgPayForBlob(signer string, blob *tmproto.Blob) (*MsgPayForBlob, error) {
> and that feels really clunky to me

Yeah I agree. I saw that in your other PR and was like meh. 

Yeah I like the idea

```go
type Blob = tmproto.Blob

func NewMsgPayForBlobs(signer string, blobs Blob...)

func NewBlob(namespace, data []byte) // uses default

// and together
msg := NewMsgPayForBlobs("callum", NewBlob("chat", "gm"), NewBlob("chat", "gn"))
```

2023-01-11 14:29 UTC, merged