Enable snapshots
celestiaorg/celestia-app pull request #1239
Opened 2023-01-15 07:50 UTC by freshe4qa

Enable snapshots for testnet to enable validators to more quickly deploy nodes/run experiments

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-01-15 16:54 UTC, freshe4qa commented
Try using a newer version of "go".

2023-01-16 05:21 UTC, evan-forbes reviewed
thanks for this!!

I believe all we have to do is to fix the linter before we merge, but I have yet to test this change.

2023-01-16 05:44 UTC, freshe4qa commented
Okey, cool

2023-01-16 08:50 UTC, cmwaters requested changes
Thanks @freshe4qa for the PR. Just needs a touch up and then we can merge it

2023-01-16 08:50 UTC, cmwaters commented on cmd/celestia-appd/cmd/root.go
> +                baseapp.SetSnapshotKeepRecent(cast.ToUint32(appOpts.Get(server.FlagStateSyncSnapshotKeepRecent))),
```suggestion
		baseapp.SetSnapshot(snapshotStore, snapshottypes.NewSnapshotOptions(cast.ToUint64(appOpts.Get(server.FlagStateSyncSnapshotInterval)), cast.ToUint32(appOpts.Get(server.FlagStateSyncSnapshotKeepRecent)))
```
I think my formatting is off but I believe this is all one function now.

2023-01-16 10:21 UTC, freshe4qa commented
I corrected it, check.

2023-01-16 11:08 UTC, freshe4qa commented
I think we need to work on fixing the "lint".

2023-01-16 11:11 UTC, cmwaters commented
Yeah just did that now

2023-01-16 11:26 UTC, freshe4qa commented
Okey, cool.

2023-01-16 11:27 UTC, cmwaters approved these changes
Looks like everything is passing. Thanks for the PR

2023-01-16 11:28 UTC, merged