Update go.mod
celestiaorg/celestia-app pull request #1242
Opened 2023-01-16 16:41 UTC by freshe4qa

important patches

## Overview

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-01-16 17:07 UTC, evan-forbes requested changes
thanks for attempting this @freshe4qa, but I would like some clarity on why some of these changes were made.

any changes to the go.mod should be done via `go mod tidy` and not manually changes unless we have a specific reason to change.

I see changes relating to grpc and the grpc-gateway that puts us ahead of our fork of the cosmos-sdk, which we have avoided doing in the past, why should we do them now?

2023-01-16 17:18 UTC, freshe4qa commented on go.mod
> +	google.golang.org/grpc v1.52.0
I know. I didn't have time to explain. Did an update for you to update what you need. And what you don't need to update, return to the previous version.

2023-01-17 12:10 UTC, freshe4qa commented
It would be good to review go.sum

2023-01-24 21:48 UTC, rootulp commented
hey @freshe4qa thanks for attempting to update our dependencies. As @evan-forbes said, celestia-app delays the upgrade of certain dependencies until cosmos-sdk performs them. The usual flow is:
1. cosmos/cosmos-sdk releases a new version
2. celestiaorg/cosmos-sdk pulls in upstream changes
3. celestia-app bumps its dependency of celestiaorg/cosmos-sdk and simultaneously takes updates for things like grpc

So let's close this PR. If there's a dependency you think needs to be upgraded ASAP (i.e. a security vulnerability) then please reach out to us at security@celestia.org

2023-01-24 21:48 UTC, closed without merging