chores: QGB keepers specific errors
celestiaorg/celestia-app pull request #1431
Opened 2023-02-28 07:24 UTC by phamminh0811

## Overview

closes #1390, this pr add some specific errors on QGB keepers data commitment and make sure previous tests success

## Checklist

- [ ] New and updated code has appropriate documentation
- [x] New and updated code has new updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-02-28 09:48 UTC, SweeXordious requested changes
Thanks a lot for handling this :+1: :+1: :rocket: 

Left some blocking comments, ping me to re-review when they're addressed

2023-02-28 09:48 UTC, SweeXordious commented on testutil/testnode/full_node.go
> +		require.NoError(t, removeDir(path.Join([]string{tmCfg.RootDir, "config"}...)))
[blocking]
Could you revert this change please? This is introduced in another PR

2023-02-28 09:48 UTC, SweeXordious commented on testutil/testnode/full_node.go
> +
[blocking]
Similar, could you please revert?

2023-02-28 09:48 UTC, SweeXordious commented on testutil/testnode/rpc_client.go
> +		return nil
[blocking]
same

2023-02-28 09:48 UTC, SweeXordious commented on testutil/testnode/rpc_client.go
> -// removeDir removes the directory `rootDir`.
[blocking]
same

2023-02-28 09:48 UTC, SweeXordious commented on x/qgb/types/errors.go
> +	ErrDataCommitmentNotGenerated			 = sdkerrors.Register(ModuleName, 29, "there is no data commitment has been generated")
[blocking]
Could you please run ` $ gofumpt -l -w .` to correctly format this?

2023-02-28 09:48 UTC, SweeXordious commented on x/qgb/types/errors.go
> +	ErrDataCommitmentNotGenerated			 = sdkerrors.Register(ModuleName, 29, "there is no data commitment has been generated")
```suggestion
	ErrDataCommitmentNotGenerated			 = sdkerrors.Register(ModuleName, 29, "no data commitment has been generated for the provided height")
```

2023-02-28 09:48 UTC, SweeXordious commented on x/qgb/keeper/keeper_data_commitment.go
> +	return types.DataCommitment{}, sdkerrors.Wrap(types.ErrDataCommitmentNotFound, "last data commitment not found")
```suggestion
	return types.DataCommitment{}, types.ErrDataCommitmentNotFound
```

I think we don't need to wrap if we're already providing the error that has the same message

2023-02-28 09:48 UTC, SweeXordious commented on x/qgb/keeper/keeper_data_commitment.go
> +			return types.DataCommitment{}, sdkerrors.Wrapf(types.ErrAttestationNotFound, fmt.Sprintf("couldn't find attestation with nonce %d", latestNonce-i))
```suggestion
			return types.DataCommitment{}, sdkerrors.Wrapf(types.ErrAttestationNotFound, fmt.Sprintf("nonce %d", latestNonce-i))
```

I think no need to repeat the message

2023-02-28 09:48 UTC, SweeXordious commented on x/qgb/keeper/keeper_data_commitment.go
> +			return types.DataCommitment{}, sdkerrors.Wrap(types.ErrAttestationNotFound, fmt.Sprintf("couldn't find attestation with nonce %d", i))
```suggestion
			return types.DataCommitment{}, sdkerrors.Wrap(types.ErrAttestationNotFound, fmt.Sprintf("nonce %d", i))
```

2023-02-28 09:48 UTC, SweeXordious commented on x/qgb/keeper/keeper_data_commitment.go
> +				"no data commitment has been generated for the provided height. Last height %d < %d",
```suggestion
				"Last height %d < %d",
```

2023-02-28 10:23 UTC, phamminh0811 commented
> Thanks a lot for handling this +1 +1 rocket
> 
> Left some blocking comments, ping me to re-review when they're addressed

it's all resolved, please check

2023-02-28 13:47 UTC, SweeXordious approved these changes
:rocket: :rocket:

2023-03-03 18:14 UTC, evan-forbes approved these changes
thanks @phamminh0811

2023-03-03 18:14 UTC, merged