chore: add mutex on KeyringSigner for QueryAccount
celestiaorg/celestia-app pull request #160
Opened 2021-12-05 10:25 UTC by albttx

## Description

closes: #143

2021-12-06 21:09 UTC, Wondertan reviewed
Hello @albttx. Thanks for PR. A question: why do you think we need a mutex there? AFAIU, we don't use the method concurrently. Although, it does not hurt to have it. Also, the synchronization should likely be consistent with all other methods altering private fields.

2021-12-06 21:09 UTC, Wondertan commented on x/payment/types/builder.go
> +	defer k.Unlock()
We should not lock the mutex for the entire network request inside `QueryAccount`. Instead, the lock should be applied to the read/write of shared memory.

2021-12-07 13:19 UTC, evan-forbes requested changes
Thanks for doing this @albttx! We appreciate this a lot.

I agree with @Wondertan, we only need to enforce a lock when reading and writing. Therefore, we simply have to lock after making the request instead of before, and then another write lock here
https://github.com/celestiaorg/lazyledger-app/blob/b6eafb59e4141fdd8891c964c261511a5fc01678/x/payment/types/builder.go#L134-L142

we also have to create a read lock when we access the sequence and account numbers to create a transaction.

https://github.com/celestiaorg/lazyledger-app/blob/b6eafb59e4141fdd8891c964c261511a5fc01678/x/payment/types/builder.go#L77-L107

thanks again, and definitely let me know if you have any further questions :slightly_smiling_face:

2021-12-07 13:26 UTC, evan-forbes commented
also, @Wondertan 
> A question: why do you think we need a mutex there? AFAIU, we don't use the method concurrently. Although, it does not hurt to have it.

As you stated, the only reason to include it is that it doesn't hurt to have it. While we don't use in a fashion that requires it, it is meant to code used as a library for clients, so I think the extra protection is warranted and should have been added when this code was initially introduced.

2021-12-07 17:29 UTC, albttx commented
Hello @evan-forbes i've just updated my PR, thanks for the explanations

So now all `KeyringSigner.{accountNumber,sequence}` are now mutex protected.

2021-12-07 17:47 UTC, evan-forbes approved these changes
perfect, thanks! :purple_heart: :sparkles:

2021-12-07 17:47 UTC, evan-forbes commented on x/payment/types/builder.go
> +	k.RUnlock()
:+1:

2021-12-07 18:02 UTC, albttx commented
Hello, sorry i just noticed that some tests were broken, the `sync.RWMutex` was a pointer, wich is not required, just the methods on `KeyringSigner` need to be

2021-12-07 20:43 UTC, evan-forbes commented
yeah good call, let's figure out all the linting and tests before merging

2021-12-08 09:42 UTC, albttx commented
updated, could you restart the linter please :)

2021-12-08 15:28 UTC, evan-forbes approved these changes
super dope, @albttx 

thanks for fixing everything!

2021-12-08 15:29 UTC, merged