update err msg of blocked params
celestiaorg/celestia-app pull request #1709
Opened 2023-05-05 21:06 UTC by NishantKoyalwar

## Overview

- updated err message to 
``` go
var ErrBlockedParameter = sdkerrors.Register(ModuleName, baseErrorCode, "parameter can not be modified")
```
- closes #1705

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [ ] Linked issues closed with keywords

2023-05-05 21:21 UTC, rootulp submitted a review, later dismissed

2023-05-05 21:22 UTC, evan-forbes approved these changes
thanks @NishantKoyalwar !

2023-05-05 21:25 UTC, evan-forbes requested changes

2023-05-05 21:25 UTC, evan-forbes commented on x/paramfilter/types.go
> +var ErrBlockedParameter = sdkerrors.Register(ModuleName, baseErrorCode, "parameter can not be modified")
the CI will break cause we hardcoded a test, so we should also update

https://github.com/celestiaorg/celestia-app/blob/2dc35d96b11496097c5ae3da226a67b880bb6c97/x/paramfilter/test/param_filter_test.go#L54

2023-05-06 21:42 UTC, evan-forbes approved these changes

2023-05-08 13:18 UTC, rootulp approved these changes

2023-05-08 13:19 UTC, merged