fix: enable authzs MsgExec to be used in a blobTx
celestiaorg/celestia-app pull request #1775
Opened 2023-05-16 10:37 UTC by cmwaters

Closes: https://github.com/celestiaorg/celestia-app/issues/1773

2023-05-16 20:52 UTC, rootulp requested changes
LGTM after one comment

2023-05-16 20:52 UTC, rootulp commented on app/test/process_proposal_test.go
> +		}
[blocking] I think this is residual from development

```suggestion
```

2023-05-16 20:52 UTC, rootulp commented on x/blob/types/blob_tx_test.go
> +		},
👍

2023-05-17 14:31 UTC, rootulp approved these changes

2023-05-18 14:20 UTC, evan-forbes commented
per synchronous discussions, I don't think we're moving forward with including authz blob support in the v1.0.0 release candidate, so should we still merge this?

2023-05-19 09:04 UTC, cmwaters commented
> per synchronous discussions, I don't think we're moving forward with including authz blob support in the v1.0.0 release candidate, so should we still merge this?

Nope, If you don't mind I'm going to put this back into draft mode and we can reassess it after cutting v1.0.0

2024-06-12 08:52 UTC, cmwaters commented
Closing as stale

2024-06-12 08:52 UTC, closed without merging