Issue fix https://github.com/celestiaorg/celestia-app/issues/2026
celestiaorg/celestia-app pull request #2035
Opened 2023-07-05 13:13 UTC by Frenzoid

## Overview

![imagen](https://github.com/celestiaorg/celestia-app/assets/30338644/09051713-e741-4a52-9f65-1877daed67ed)

## Checklist

- [X] New and updated code has appropriate documentation
- [X] New and updated code has new and/or updated testing
- [X] Required CI checks are passing
- [X] Visual proof for any user facing features like CLI or documentation updates
- [X] Linked issues closed with keywords

2023-07-05 13:43 UTC, evan-forbes reviewed
thanks for handling this @Frenzoid !

2023-07-05 13:43 UTC, evan-forbes commented on test/util/testnode/full_node.go
> +	}
this was a good idea @Frenzoid, but using a string of "" is valid, so we can just leave it up to the users on this one

all we have to do is blindly use the chain-id in the config

2023-07-05 13:43 UTC, evan-forbes commented
also, don't worry about the docker build CI failing, it will for all PRs from forks. we should expect the rest to pass though before merging

2023-07-05 13:53 UTC, rootulp commented
@Frenzoid this repo attempts to conform to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) so I renamed the PR title b/c the PR title will be used as the default commit message for the squashed commit that ends up on main.

2023-07-05 14:12 UTC, Frenzoid commented
Thank you all for the feeback, tbh its the first time i've seen this repo, and i've reached to it from LW3 :)

2023-07-06 20:36 UTC, Frenzoid commented on test/util/testnode/full_node.go
> +	}
I see, that make sense, on it right now :)

2023-07-06 22:35 UTC, rootulp requested changes
@Frenzoid golangci-lint is complaining b/c this import is no longer used:

```go
	tmrand "github.com/tendermint/tendermint/libs/rand"
```

I can't comment directly on the line but it should be removed

2023-07-07 13:15 UTC, evan-forbes approved these changes
approving pending CI :slightly_smiling_face: 

thanks again @Frenzoid

2023-07-07 13:28 UTC, rootulp approved these changes

2023-07-10 07:19 UTC, cmwaters approved these changes

2023-07-10 18:21 UTC, merged