README.md: Update `celes` to `uceles`
celestiaorg/celestia-app pull request #210
Opened 2022-02-11 12:54 UTC by renaynay

This PR updates the `README.md` to use the current denom which is `uceles` instead of `celes`.

2022-02-11 13:21 UTC, marbar3778 submitted a review, later dismissed

2022-02-11 13:56 UTC, adlerjohn submitted a review, later dismissed

2022-02-19 08:34 UTC, liamsi approved these changes

2022-02-20 19:37 UTC, evan-forbes requested changes
running these commands as is doesn't actually work, we need to add an extra digit when we `gentx`.

should have been changed a long time ago, but we never did :grimacing:

2022-02-21 22:10 UTC, evan-forbes approved these changes

2022-02-21 22:10 UTC, merged