Resolved unnecessary usage of -mod=readonly
celestiaorg/celestia-app pull request #2343
Opened 2023-08-24 17:23 UTC by Vikramop

## Overview
 Resolved unnecessary usage of -mod=readonly

## Checklist

- [ ] New and updated code has appropriate documentation
- [ ] New and updated code has new and/or updated testing
- [ ] Required CI checks are passing
- [ ] Visual proof for any user facing features like CLI or documentation updates
- [x] Linked issues closed with keywords

2023-08-24 17:24 UTC, rootulp requested changes
Can this PR please remove all instances of `-mod=readonly` in the Makefile?

2023-08-24 17:26 UTC, rootulp commented
I updated the PR title to conform to conventional commits: https://www.conventionalcommits.org/en/v1.0.0/

2023-08-24 17:26 UTC, Vikramop commented
> Can this PR please remove all instances of `-mod=readonly` in the Makefile?

It remove only the one you have indicated.

2023-08-24 17:29 UTC, Vikramop commented
So I've to remove all the -mod=readonly from the makefile.

2023-08-24 17:33 UTC, Vikramop commented
Removed all the 7 -mod=readonly.

2023-08-24 17:44 UTC, rootulp submitted a review, later dismissed

2023-08-24 17:46 UTC, rootulp commented
Thanks for the contribution @Vikramop 🎊

2023-08-25 02:25 UTC, Vikramop commented
> Thanks for the contribution @Vikramop 🎊

Happy to contribute.

2023-08-27 16:18 UTC, rootulp approved these changes

2023-08-27 16:18 UTC, rootulp commented on Makefile
> +	@go install  $(BUILD_FLAGS) ./cmd/celestia-appd
```suggestion
	@go install $(BUILD_FLAGS) ./cmd/celestia-appd
```

2023-08-27 16:18 UTC, rootulp commented on Makefile
> +	@go test  -timeout 30m ./...
```suggestion
	@go test -timeout 30m ./...
```

2023-08-27 16:18 UTC, rootulp commented on Makefile
> +	@go test  ./... -short
```suggestion
	@go test ./... -short
```

2023-08-27 16:18 UTC, rootulp commented on Makefile
> +	@KNUU_NAMESPACE=celestia-app E2E=true go test  ./test/e2e/... -timeout 30m
```suggestion
	@KNUU_NAMESPACE=celestia-app E2E=true go test ./test/e2e/... -timeout 30m
```

2023-08-27 16:18 UTC, rootulp commented on Makefile
> +	@go test  -bench=. ./...
```suggestion
	@go test -bench=. ./...
```

2023-08-27 16:18 UTC, rootulp commented on Makefile
> +	@go install  $(BUILD_FLAGS) ./test/cmd/txsim
```suggestion
	@go install $(BUILD_FLAGS) ./test/cmd/txsim
```

2023-08-27 16:19 UTC, rootulp commented
Resolved merge conflicts and removed a residual space from each ocurrence.

2023-08-27 16:19 UTC, rootulp approved these changes

2023-08-28 08:14 UTC, cmwaters approved these changes

2023-08-28 08:14 UTC, merged