Add back the governance module
celestiaorg/celestia-app pull request #272
Opened 2022-04-04 22:17 UTC by liamsi

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Review `Codecov Report` in the comment section below once CI passes

2022-04-04 22:23 UTC, liamsi commented on app/app.go
> +		// TODO: do we want a community pool at all? If not, does it even make sense to include that NewCommunityPoolSpendProposalHandler?
Let's discuss the community pool in a separate issue/github dicsussion thread. I'll remove the todo after we have that issue/discusssion.

2022-04-05 04:06 UTC, evan-forbes approved these changes
Yay! Thanks for adding this back in!

2022-04-05 04:14 UTC, evan-forbes requested changes
whoops, sorry, reviewed my phone and got too excited. setting a block so we don't accidentally merge before we set the gov module account.

2022-04-05 12:29 UTC, liamsi commented
> before we set the gov module account

What do you mean?

2022-04-05 12:46 UTC, liamsi commented on app/app.go
> +		govtypes.ModuleName:            {authtypes.Burner},
Did you mean this by your comment?

2022-04-08 13:02 UTC, liamsi commented
I think these are all the changes necessary to add back the governance module. While modifying the code, I've realized that we could restructure files/packages slightly to make it more readable/accessible. I think we can slowly move away from the way starport generates and structures everything. But that is orthogonal to this PR.

Either way, turning this into ready for review now.

2022-04-10 00:48 UTC, adlerjohn submitted a review, later dismissed
utACK

2022-04-10 08:50 UTC, liamsi commented on app/app.go
> +		// TODO: do we want a community pool at all? If not, does it even make sense to include that NewCommunityPoolSpendProposalHandler?
```suggestion
		// TODO: do we want a community pool at all? If not, does it even make sense to include that NewCommunityPoolSpendProposalHandler?
```

2022-04-10 17:29 UTC, evan-forbes commented on app/app.go
> +		govtypes.ModuleName:            {authtypes.Burner},
yep! everything should be good to go

2022-04-10 17:30 UTC, evan-forbes submitted a review, later dismissed
:+1:

2022-04-10 17:30 UTC, evan-forbes commented
fairly certain that the linter is only failing because of what was already fixed in https://github.com/celestiaorg/celestia-app/pull/273

2022-04-10 17:40 UTC, evan-forbes commented
> While modifying the code, I've realized that we could restructure files/packages slightly to make it more readable/accessible.

I agree. I like what osmosis does here by separating the modules out into their own file. We could likely do this with even more components of the app.

https://github.com/osmosis-labs/osmosis/blob/main/app/modules.go

2022-04-10 17:43 UTC, liamsi commented
> fairly certain that the linter is only failing because of what was already fixed in https://github.com/celestiaorg/celestia-app/pull/273

Let me rebase to be more certain :)

> I like what osmosis does here by separating the modules out into their own file. We could likely do this with even more components of the app.

Yes, exactly. I also thought Osmosis was a good example here!

2022-04-10 17:48 UTC, liamsi commented
> fairly certain that the linter is only failing because of what was already fixed in https://github.com/celestiaorg/celestia-app/pull/273

confirmed, thanks

2022-04-10 17:49 UTC, liamsi commented on app/app.go
> +		// TODO: do we want a community pool at all? If not, does it even make sense to include that NewCommunityPoolSpendProposalHandler?
Actually. Let's remove this TODO. We should rather track this in an issue if anything. We had a community pool all along btw (with no governance to govern the tokens in that pool 😬).
```suggestion
		// TODO: do we want a community pool at all? If not, does it even make sense to include that NewCommunityPoolSpendProposalHandler?
```

2022-04-11 03:24 UTC, adlerjohn approved these changes
utACK

2022-04-11 14:42 UTC, merged