chore: move ica upgrade test to test
celestiaorg/celestia-app pull request #3302
Opened 2024-04-11 15:59 UTC by ninabarbakadze

## Overview

2024-04-11 18:33 UTC, rootulp approved these changes
Thanks!

2024-04-11 18:33 UTC, rootulp commented on test/util/testapp_upgrade.go
> +package util
[not blocking] FYI: https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

2024-04-12 11:55 UTC, cmwaters approved these changes
The other approach would be to say that these are all upgrade tests and just to bundle them up together rather than adding a new test for each new module

2024-04-12 11:55 UTC, cmwaters commented on test/util/testapp_upgrade.go
> +func SetupTestApp(t *testing.T, upgradeHeight int64) (*app.App, keyring.Keyring) {
nit: 
```suggestion
func SetupTestAppWithUpgradeHeight(t *testing.T, upgradeHeight int64) (*app.App, keyring.Keyring) {
```

2024-04-15 19:56 UTC, rootulp approved these changes

2024-04-16 09:21 UTC, cmwaters requested changes
You're still repeating yourself a lot here. This kind of pattern lends itself to table based testing.

```go
testCases := []struct {
	module string
	preUpgradeAssertion func (t *testing.T, app *app.App)
	postUpgradeAssertion func(t *testing.T, app *app.App)
}{
	{
		module: "signal",
		preUpgradeAssertion: func(t *testing.T, app *app.App, ) {
			// add assertions about how this module doesn't yet exist
		},
		postUpgradeAssertion: func(t *testing.T, app *app.App) {
			// add assertions about how this module now exists
		},
	},
}

// start up the testnet

// do the pre upgrade assertions for all testCases

// upgrade the application and check it succeeded

// do all the post upgrade assertions for all testCases

```

Also don't forget that when a test errors that it tells the caller which module failed and at which stage

2024-04-17 14:33 UTC, cmwaters approved these changes
Looks good once you fix the conflicts

2024-04-18 10:37 UTC, cmwaters approved these changes

2024-04-18 12:44 UTC, evan-forbes approved these changes

2024-04-18 12:50 UTC, merged