Fixes #3078: <Run celestia-app via Docker>
celestiaorg/celestia-app pull request #4168
Opened 2024-12-28 13:19 UTC by abhirajprasad

Added Docker Installation Instructions to README.md

This PR introduces a new section in the README.md file for the celestia-app project, providing detailed instructions on how to install and run the application using Docker.

Changes Made:
 Added a comprehensive Docker installation section, including:
1. Prerequisites for Docker installation.
2. Instructions for fetching the latest tagged release of the celestia-app Docker image.
3. Steps to run the application using Docker Compose.

2025-01-02 02:29 UTC, rootulp requested changes
Thanks for working on this. I have a few nits to make this shorter and easier to read.

Also I think this needs to clarify which docker-compose.yml to use.

2025-01-02 02:29 UTC, rootulp commented on README.md
> +To start the application using Docker Compose, navigate to the directory containing your `docker-compose.yml` file and run:
which docker-compose.yml is this referring to? One exists in the local_devnet directory but I don't think that's what this refers to.

2025-01-02 02:29 UTC, rootulp commented on README.md
> +## Docker Installation
Can this be a subheading under Install at the same level as ### From source

```suggestion

### Docker
```

2025-01-02 02:29 UTC, rootulp commented on README.md
> +- Ensure you have Docker version **20.10** or higher installed. You can download it from [Docker's official website](https://www.docker.com/get-started).
This is shorter and easier to read

```suggestion
- Install [Docker](https://www.docker.com/get-started) 20.10 or higher
```

Also why was 20.10 selected?

2025-01-02 02:29 UTC, rootulp commented on README.md
> +- Allocate at least **2 CPU cores** and **4 GB of RAM** to Docker for optimal performance. This can be configured in Docker Desktop settings.
IMO we can assume that the user has done this already b/c it's part of Docker install steps

```suggestion
```

2025-01-02 02:29 UTC, rootulp commented on README.md
> +2. Fetching the Latest Tagged Release
```suggestion
2. Fetch the latest tagged release
```

2025-01-02 02:29 UTC, rootulp commented on README.md
> +To pull the latest tagged release of the `celestia-app` Docker image, run the following command:
This repeats the previous line so it's extraneous.
 
```suggestion
```

2025-01-02 02:29 UTC, rootulp commented on README.md
> +3. Running the Application
```suggestion
3. Run the application
```

2025-01-02 18:33 UTC, abhirajprasad commented on README.md
> +To start the application using Docker Compose, navigate to the directory containing your `docker-compose.yml` file and run:
yes, you are correct. 
if there is a docker-compose.yml file in the local_devnet directory, it is likely for local development and testing purposes.
the docker-compose.yml file referred to in the README should ideally be a general-purpose file that users can use to run the celestia-app in a Docker environment.

2025-01-02 18:35 UTC, abhirajprasad commented on README.md
> +- Ensure you have Docker version **20.10** or higher installed. You can download it from [Docker's official website](https://www.docker.com/get-started).
docker version 20.10 was selected just to ensure users have access to the latest features

2025-01-04 19:06 UTC, rootulp requested changes
My feedback hasn't been addressed

2025-01-05 08:58 UTC, abhirajprasad commented on README.md
> +    ```
Sure, I can move this into the docker/docker-compose.yml file in the repository. I'll make the necessary changes and commit the file. Let me know if there are any specific configurations or additions you'd like me to include.

2025-01-06 17:41 UTC, rootulp commented
The README doesn't conform to markdownlint. The docker-compose.yml file isn't valid. I'll fix and push

2025-01-06 17:42 UTC, rootulp requested changes

2025-01-06 17:42 UTC, rootulp commented on docker/docker-compose.yml
> +       command: ["celestia-appd", "start"]
this command doesn't work. The Docker container doesn't start:

```
2025-01-06 12:40:33 Starting celestia-appd with command:
2025-01-06 12:40:33 /bin/celestia-appd celestia-appd start
2025-01-06 12:40:33 
2025-01-06 12:40:33 Error: unknown command "celestia-appd" for "celestia-appd"
2025-01-06 12:40:33 Run 'celestia-appd --help' for usage.
```

2025-01-06 17:42 UTC, rootulp commented on docker/docker-compose.yml
> +version: '3'
This is no longer needed

```
$ docker compose up --detach
WARN[0000] /Users/rootulp/git/rootulp/celestiaorg/celestia-app/docker/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```

2025-01-06 17:42 UTC, rootulp commented on docker/docker-compose.yml
> +   services:
the indentation here is incorrect

2025-01-06 17:42 UTC, rootulp commented on README.md
> +    ```
this doesn't conform to markdownlint.

2025-01-07 08:09 UTC, abhirajprasad commented on docker/docker-compose.yml
> +version: '3'
Yes you are right the version field is obsolete in modern Docker Compose configurations, so I will remove that line to align with current standards.

2025-01-07 08:16 UTC, abhirajprasad commented on docker/docker-compose.yml
> +version: '3'
Thanks for reviewing @rootulp. I ran it on my machine, but it failed to start because of some issues with the configuration and  commands

2025-01-07 08:17 UTC, abhirajprasad commented on docker/docker-compose.yml
> +version: '3'
After modifying the compose file, I was able to get it running successfully

2025-01-07 08:19 UTC, abhirajprasad commented on docker/docker-compose.yml
> +version: '3'
I'm committing the updated docker-compose file, the validator now starts and remains up as expected. Let me know if you’d like any details about the changes I made!

2025-01-07 13:35 UTC, rootulp commented on docker/docker-compose.yml
> +
```suggestion
```

2025-01-07 13:35 UTC, rootulp commented on docker/docker-compose.yml
> +        celestia-appd start --rpc.laddr tcp://0.0.0.0:26657"
it's confusing for this local chain to re-use the same chain-id as Mainnet Beta. Can this instead use the chain-id `test`?

https://github.com/celestiaorg/celestia-app/blob/e4c9f2d607c24f3d67bc3c9442c195f3d626700f/scripts/single-node.sh#L17

2025-01-07 18:40 UTC, abhirajprasad commented on docker/docker-compose.yml
> +        celestia-appd start --rpc.laddr tcp://0.0.0.0:26657"
yes, we can change the chain ID to "test" to avoid confusion with the mainnet

2025-01-07 19:57 UTC, rootulp commented on docker/docker-compose.yml
> +services:
it still doesn't work

```
2025-01-07 14:56:01 Starting celestia-appd with command:
2025-01-07 14:56:01 /bin/celestia-appd sh -c 
2025-01-07 14:56:01   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:01     celestia-appd init  --chain-id  &&
2025-01-07 14:56:01     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:01     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:01     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:01     celestia-appd collect-gentxs
2025-01-07 14:56:01   fi &&
2025-01-07 14:56:01   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:01 
2025-01-07 14:56:02 Error: unknown command "sh" for "celestia-appd"
2025-01-07 14:56:02 
2025-01-07 14:56:02 Did you mean this?
2025-01-07 14:56:02     tx
2025-01-07 14:56:02 
2025-01-07 14:56:02 Run 'celestia-appd --help' for usage.
2025-01-07 14:56:03 Error: unknown command "sh" for "celestia-appd"
2025-01-07 14:56:03 
2025-01-07 14:56:03 Did you mean this?
2025-01-07 14:56:03     tx
2025-01-07 14:56:03 
2025-01-07 14:56:03 Run 'celestia-appd --help' for usage.
2025-01-07 14:56:03 Error: unknown command "sh" for "celestia-appd"
2025-01-07 14:56:03 
2025-01-07 14:56:03 Did you mean this?
2025-01-07 14:56:03     tx
2025-01-07 14:56:03 
2025-01-07 14:56:03 Run 'celestia-appd --help' for usage.
2025-01-07 14:56:04 Error: unknown command "sh" for "celestia-appd"
2025-01-07 14:56:04 
2025-01-07 14:56:04 Did you mean this?
2025-01-07 14:56:04     tx
2025-01-07 14:56:04 
2025-01-07 14:56:04 Run 'celestia-appd --help' for usage.
2025-01-07 14:56:02 Starting celestia-appd with command:
2025-01-07 14:56:02 /bin/celestia-appd sh -c 
2025-01-07 14:56:02   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:02     celestia-appd init  --chain-id  &&
2025-01-07 14:56:02     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:02     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:02     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:02     celestia-appd collect-gentxs
2025-01-07 14:56:02   fi &&
2025-01-07 14:56:02   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:02 
2025-01-07 14:56:03 Starting celestia-appd with command:
2025-01-07 14:56:03 /bin/celestia-appd sh -c 
2025-01-07 14:56:03   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:03     celestia-appd init  --chain-id  &&
2025-01-07 14:56:03     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:03     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:03     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:03     celestia-appd collect-gentxs
2025-01-07 14:56:03   fi &&
2025-01-07 14:56:03   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:03 
2025-01-07 14:56:04 Starting celestia-appd with command:
2025-01-07 14:56:04 /bin/celestia-appd sh -c 
2025-01-07 14:56:04   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:04     celestia-appd init  --chain-id  &&
2025-01-07 14:56:04     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:04     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:04     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:04     celestia-appd collect-gentxs
2025-01-07 14:56:04   fi &&
2025-01-07 14:56:04   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:04 
2025-01-07 14:56:05 Starting celestia-appd with command:
2025-01-07 14:56:05 /bin/celestia-appd sh -c 
2025-01-07 14:56:05   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:05     celestia-appd init  --chain-id  &&
2025-01-07 14:56:05     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:05     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:05     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:05     celestia-appd collect-gentxs
2025-01-07 14:56:05   fi &&
2025-01-07 14:56:05   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:05 
2025-01-07 14:56:07 Starting celestia-appd with command:
2025-01-07 14:56:07 /bin/celestia-appd sh -c 
2025-01-07 14:56:07   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:07     celestia-appd init  --chain-id  &&
2025-01-07 14:56:07     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:07     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:07     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:07     celestia-appd collect-gentxs
2025-01-07 14:56:07   fi &&
2025-01-07 14:56:07   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:07 
2025-01-07 14:56:11 Starting celestia-appd with command:
2025-01-07 14:56:11 /bin/celestia-appd sh -c 
2025-01-07 14:56:11   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:11     celestia-appd init  --chain-id  &&
2025-01-07 14:56:11     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:11     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:11     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:11     celestia-appd collect-gentxs
2025-01-07 14:56:11   fi &&
2025-01-07 14:56:11   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:11 
2025-01-07 14:56:18 Starting celestia-appd with command:
2025-01-07 14:56:18 /bin/celestia-appd sh -c 
2025-01-07 14:56:18   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:18     celestia-appd init  --chain-id  &&
2025-01-07 14:56:18     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:18     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:18     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:18     celestia-appd collect-gentxs
2025-01-07 14:56:18   fi &&
2025-01-07 14:56:18   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:18 
2025-01-07 14:56:31 Starting celestia-appd with command:
2025-01-07 14:56:31 /bin/celestia-appd sh -c 
2025-01-07 14:56:31   if [ ! -f /root/.celestia-app/config/genesis.json ]; then
2025-01-07 14:56:31     celestia-appd init  --chain-id  &&
2025-01-07 14:56:31     celestia-appd keys add validator --keyring-backend test &&
2025-01-07 14:56:31     celestia-appd add-genesis-account $(celestia-appd keys show validator -a --keyring-backend test) 10000000000utia &&
2025-01-07 14:56:31     celestia-appd gentx validator 1000000000utia --chain-id  --keyring-backend test &&
2025-01-07 14:56:31     celestia-appd collect-gentxs
2025-01-07 14:56:31   fi &&
2025-01-07 14:56:31   celestia-appd start --rpc.laddr tcp://0.0.0.0:26657
2025-01-07 14:56:31 
2025-01-07 14:56:05 Error: unknown command "sh" for "celestia-appd"
2025-01-07 14:56:05 
2025-01-07 14:56:05 Did you mean this?
2025-01-07 14:56:05     tx
2025-01-07 14:56:05 
2025-01-07 14:56:05 Run 'celestia-appd --help' for usage.
2025-01-07 14:56:07 Error: unknown command "sh" for "celestia-appd"
202 [...]

2025-01-07 19:57 UTC, rootulp commented
Also I'm observing these warnings:

```
$ docker compose up --detach
WARN[0000] The "MONIKER" variable is not set. Defaulting to a blank string.
WARN[0000] The "CHAIN_ID" variable is not set. Defaulting to a blank string.
WARN[0000] The "CHAIN_ID" variable is not set. Defaulting to a blank string.
```

2025-01-10 18:52 UTC, abhirajprasad commented
Hi @rootulp, as you earlier mentioned there’s already a docker-compose.yml file in the local_devnet directory, but it seems designed for multiple nodes. So I’m a bit confused—do we need to create a new docker-compose.yml file specifically for running a single node, or can we use the existing one?

2025-03-14 18:39 UTC, rootulp commented
Closing because stale. Please re-open if still relevant.

2025-03-14 18:39 UTC, closed without merging